### ISSUE TITLE
Time for a new gem version

### ISSUE THREAD

**Issue by andrewhavens** [infinitered/ruby-xcdm#25]
Looks like there's an important bugfix that has been merged into the master branch. I'm not sure who has access to release new gem versions, but it would be nice to release a new version of the gem. New Red Potion projects currently fail to compile if you have Xcode 10 installed.

**Comment by amirrajan** [comment]
@kemiller if you can give me access on ruby gems, I can handle the deployments.

**Comment by kemiller** [comment]
No problem, Amir.  What's your gems username?

**Comment by kemiller** [comment]
Nevermind I found you.  It's done.

**Comment by andrewhavens** [comment]
@wndxlori has already released the new gem version: 0.0.11
